# Generated by Django 3.1 on 2020-10-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elixir_app', '0002_users_expert'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardid', models.CharField(max_length=500)),
                ('blood', models.CharField(max_length=500)),
                ('age', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
            ],
        ),
    ]
