# Generated by Django 3.1 on 2020-10-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elixir_app', '0003_patientdetails'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patientdetails',
            table='elixir_app_patientdetails',
        ),
    ]
