# Generated by Django 3.1 on 2020-10-17 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elixir_app', '0005_auto_20201015_2323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users_Expert',
        ),
    ]
