# Generated by Django 3.1 on 2020-10-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elixir_app', '0006_delete_users_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='blood',
            field=models.CharField(choices=[('A+', 'Male'), ('A-', 'Female'), ('B+', 'Male'), ('B-', 'Female'), ('O+', 'Male'), ('O-', 'Female'), ('AB+', 'Male'), ('AB-', 'Female')], max_length=100),
        ),
    ]
