# Generated by Django 3.1 on 2020-10-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elixir_app', '0007_auto_20201017_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='blood',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=100),
        ),
    ]
