# Generated by Django 3.1 on 2020-10-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elixir_app', '0008_auto_20201017_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insert',
            name='filepaths',
            field=models.ImageField(upload_to='images'),
        ),
    ]
