# Generated by Django 3.1 on 2020-10-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elixir_app', '0009_auto_20201023_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insert',
            name='filepaths',
            field=models.FileField(max_length=200, upload_to='images'),
        ),
    ]
