# Generated by Django 3.1 on 2020-10-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elixir_app', '0010_auto_20201023_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insert',
            name='filepaths',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
