# Generated by Django 3.1 on 2020-10-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elixir_app', '0011_auto_20201023_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insert',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
