# Generated by Django 3.1 on 2020-10-24 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elixir_app', '0012_auto_20201024_2322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insert',
            new_name='InsertImage',
        ),
    ]
